name = ESF
description = Layout specific to the ESF project.
preview = preview.png
template = simple-layout

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
;regions[postscript]     = Postsript
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/esf/esf.layout.css
