; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.23"

; Modules
projects[views_bulk_operations][version] = "3.1"

projects[admin_views][version] = "1.2"

projects[backup_migrate][version] = "2.8"

projects[breakpoints][version] = "1.1"

projects[ctools][version] = "1.3"

projects[bundle_copy][version] = "1.1"

projects[ckeditor][version] = "1.13"

projects[context][version] = "3.1"

projects[context_omega][version] = "1.1"

projects[db_maintenance][version] = "1.1"

projects[diff][version] = "3.2"

projects[eck][version] = "2.0-rc2"

projects[email][version] = "1.2"

projects[entity][version] = "1.2"

projects[entityreference][version] = "1.1"

projects[features_extra][version] = "1.0-beta1+3-dev"

projects[features][version] = "2.0"

projects[field_group][version] = "1.3"

projects[file_entity][version] = "2.0-alpha3"

projects[filefield_paths][version] = "1.0-beta4"

projects[i18n][version] = "1.10"

projects[imce][version] = "1.7"

projects[imce_wysiwyg][version] = "1.0"

projects[inline_entity_form][version] = "1.3"

projects[jquery_update][version] = "2.3"

projects[l10n_client][version] = "1.3"

projects[l10n_update][version] = "1.0-beta3"

projects[libraries][version] = "2.1"

projects[link][version] = "1.2"

projects[media][version] = "2.0-alpha3"

projects[menu_block][version] = "2.3"

projects[module_filter][version] = "1.8"

projects[navbar][version] = "1.0-beta1"

projects[node_export][version] = "3.0"

projects[references][version] = "2.1"

projects[password_field][version] = "1.0-beta1"

projects[pathauto][version] = "1.2"

projects[pdm][version] = "1.0"

projects[quicktabs][version] = "3.6"

projects[simplified_menu_admin][version] = "1.0-beta2"

projects[site_map][version] = "1.0"

projects[taxonomy_breadcrumb][version] = "1.x-dev"

projects[token][version] = "1.5"

projects[translation_table][version] = "1.0-beta1"

projects[transliteration][version] = "3.1"

projects[uuid][version] = "1.0-alpha5"

projects[variable][version] = "2.3"

projects[viewfield][version] = "2.0"

projects[views][version] = "3.7"

projects[weight][version] = "2.3"

projects[workbench][version] = "1.2"

projects[workbench_media][version] = "2.1"

projects[wysiwyg][version] = "2.2"

; Themes
projects[adminimal_theme][version] = "1.x-dev"

projects[ember][version] = "2.0-alpha1+41-dev"

projects[omega][version] = "4.0-rc1"

projects[rootcandy][version] = "1.0-alpha1"

projects[rubik][version] = "4.0-beta9"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = ""
libraries[modernizr][download][url] = ""
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[html5shiv][download][type] = ""
libraries[html5shiv][download][url] = ""
libraries[html5shiv][directory_name] = "html5shiv"
libraries[html5shiv][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

