; This file was auto-generated by drush make

core = 7.x
api = 2

; Projects
projects[drupal][version] = "7.23"

projects[views_bulk_operations][version] = "3.1"

projects[admin_menu][version] = "3.0-rc4"

projects[admin_views][version] = "1.2"

projects[adminimal_admin_menu][version] = "1.4"

projects[coder][version] = "2.0"

projects[breakpoints][version] = "1.1"

projects[ctools][version] = "1.3"

projects[ckeditor][version] = "1.13"

projects[commerce_devel][version] = "1.0-beta5"

projects[context][version] = "3.1"

projects[context_omega][version] = "1.1"

projects[devel][version] = "1.3"

projects[diff][version] = "3.2"

projects[eck][version] = "3.x-dev"

projects[entity][version] = "1.2"

projects[entityreference][version] = "1.0"

projects[esf_feature][download][type] = ""
projects[esf_feature][download][url] = ""
projects[esf_feature][type] = "module"
projects[esf_feature][version] = "1.15"

projects[esf_feature_ui][download][type] = ""
projects[esf_feature_ui][download][url] = ""
projects[esf_feature_ui][type] = "module"
projects[esf_feature_ui][version] = "1.3"

projects[esf_permissions][download][type] = ""
projects[esf_permissions][download][url] = ""
projects[esf_permissions][type] = "module"
projects[esf_permissions][version] = "1.2"

projects[features_extra][version] = "1.0-beta1"

projects[features][version] = "2.0"

projects[file_entity][version] = "2.0-alpha3"

projects[i18n][version] = "1.10"

projects[inline_entity_form][version] = "1.3"

projects[libraries][version] = "2.1"

projects[link][version] = "1.1"

projects[media][version] = "2.0-alpha3"

projects[metatag][version] = "1.0-beta7"

projects[module_filter][version] = "1.8"

projects[node_export][version] = "3.0"

projects[oauth][version] = "3.1"

projects[password_field][version] = "1.0-beta1"

projects[pdm][version] = "1.0"

projects[quicktabs][version] = "3.6"

projects[services][version] = "3.5"

projects[simplified_menu_admin][version] = "1.0-beta2"

projects[site_map][version] = "1.0"

projects[token][version] = "1.5"

projects[uuid][version] = "1.0-alpha5"

projects[variable][version] = "2.3"

projects[viewfield][version] = "2.0"

projects[views][version] = "3.7"

projects[weight][version] = "2.3"

projects[workbench][version] = "1.2"

projects[workbench_media][version] = "2.1"

projects[adminimal_theme][version] = "1.x-dev"

projects[ember][version] = "2.0-alpha1"

projects[omega][version] = "4.0"

projects[default][download][type] = ""
projects[default][download][url] = ""
projects[default][type] = "theme"

; Libraries
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

