name = Blue
description = Two column layout specific to the ESF project
preview = preview.png
template = blue-layout

; Regions
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[hero]           = Hero
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/hero/blue.layout.css
stylesheets[all][] = css/layouts/hero/blue.layout.no-query.css
