name = Blue
description = Two column layout specific to the ESF project
preview = preview.png
template = blue-layout

; Regions
regions[header]         = Header
regions[content]        = Content
regions[sidebar]        = Sidebar
regions[postscript]     = Postscript
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/blue/blue.layout.css
stylesheets[all][] = css/layouts/blue/blue.layout.no-query.css
