<?php

/**
 * Implements hook_menu().
 */
function esf_module_ui_menu() {
  // Top level "Store" container.
  $items['admin/config/esf'] = array(
    'title' => 'ESF Portal',
    'description' => 'ESF portal related settings.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer esf'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => -50,
  );
  
  $items['admin/config/esf/settings'] = array(
    'title' => 'Settings',
    'description' => 'Configuration of the general settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('variable_module_form', 'esf_module'),
    'access arguments' => array('administer esf'),
    'weight' => 10,
  );

  $items['admin/config/esf/remote'] = array(
    'title' => 'Remote Machine Configuration',
    'description' => 'Configuration of the connection to the remote machine.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('esf_module_ui_remote'),
    'access arguments' => array('administer esf'),
    'file' => 'includes/esf_module_ui.admin.inc',
    'weight' => 11,
  );
  
  return $items;
}