<?php

/**
 * Implements hook_menu().
 */
function muni_guacamole_ui_menu() {
  
  $items['admin/config/muni/guacamole'] = array(
    'title' => 'Guacamole configuration',
    'description' => 'Configuration of the Remote Desktop software.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('variable_module_form', 'muni_guacamole'),
    'access arguments' => array('administer muni guacamole'),
    'weight' => 10,
  );
  
  return $items;
}