name = Guacamole
description = Plain layout designed for the remote machine connection.
preview = preview.png
template = guacamole-layout

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[content]        = Content
regions[sidebar]        = Sidebar
regions[postscript]     = Postscript
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/guacamole/guacamole.layout.css
